version: "3.9"
services:
    #http server
    web:
        build: .
        env_file:
            - .env
        ports:
            - "8080:8080"
        volumes:
            - .:/usr/src/app
        command: air ./cmd/main.go -b 0.0.0.0
    #postgres db 
    db:
        image: postgres:alpine
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRE_PASSSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        ports:
            - "5432:5432"
        volumes:
            - postgres-db:/var/lib/postgresql/data

#used for persistant data even if the container turns off
volumes:
    postgres-db:

